version: "3"
services:

  bootnode:
    image: energy
    command:
      - "geth"
      - "--datadir=/datadir"
      - "--genesis=/datadir/testnet.json"
      - "--networkid=14000"
      - "--nodekeyhex=633ab917d09441de38ae9251e79ced41df39a1c338842b826c18fb1773246e18"
      - "--syncmode=full"
      - "--gcmode=archive"
      - "--http"
      - "--http.addr=0.0.0.0"
      - "--http.api=eth,net,web3,debug,trace,txpool"
      - "--http.port=8545"
      - "--http.corsdomain=*"
      - "--http.vhosts=*"
    volumes:
      - "./data/bootnode:/datadir"
      - "./genesis/testnet.json:/datadir/testnet.json"
    ports:
      - "8545:8545"
      - "8546:8546"
    restart: always

  validator_1:
    image: energy
    command:
      - "geth"
      - "--datadir=/datadir"
      - "--genesis=/datadir/testnet.json"
      - "--mine"
      - "--password=/datadir/password.txt"
      - "--allow-insecure-unlock"
      - "--unlock=0x08fae3885e299c24ff9841478eb946f41023ac69"
      - "--miner.etherbase=0x08fae3885e299c24ff9841478eb946f41023ac69"
      - "--bootnodes=enode://5c8e90050fabb7e14e4921dc107caf533140112245e7a231d0edc49861cd779760ad4804e7034952a5cc79422fa9d31c54e9a6141fb4995af7a6bfce7a39140f@bootnode:30303"
      - "--gcmode=archive"
      - "--syncmode=full"
      - "--networkid=14000"
    volumes:
      - "./data/val1:/datadir"
      - "./genesis/testnet.json:/datadir/testnet.json"
      - "./genesis/keystore:/datadir/keystore"
      - "./genesis/password.txt:/datadir/password.txt"
    restart: always
  validator_2:
    image: energy
    command:
      - "geth"
      - "--datadir=/datadir"
      - "--genesis=/datadir/testnet.json"
      - "--mine"
      - "--password=/datadir/password.txt"
      - "--allow-insecure-unlock"
      - "--unlock=0x751aaca849b09a3e347bbfe125cf18423cc24b40"
      - "--miner.etherbase=0x751aaca849b09a3e347bbfe125cf18423cc24b40"
      - "--bootnodes=enode://5c8e90050fabb7e14e4921dc107caf533140112245e7a231d0edc49861cd779760ad4804e7034952a5cc79422fa9d31c54e9a6141fb4995af7a6bfce7a39140f@bootnode:30303"
      - "--gcmode=archive"
      - "--syncmode=full"
      - "--networkid=14000"
    volumes:
      - "./data/val2:/datadir"
      - "./genesis/testnet.json:/datadir/testnet.json"
      - "./genesis/keystore:/datadir/keystore"
      - "./genesis/password.txt:/datadir/password.txt"
    restart: always
  validator_3:
    image: energy
    command:
      - "geth"
      - "--datadir=/datadir"
      - "--genesis=/datadir/testnet.json"
      - "--mine"
      - "--password=/datadir/password.txt"
      - "--allow-insecure-unlock"
      - "--unlock=0xa6ff33e3250cc765052ac9d7f7dfebda183c4b9b"
      - "--miner.etherbase=0xa6ff33e3250cc765052ac9d7f7dfebda183c4b9b"
      - "--bootnodes=enode://5c8e90050fabb7e14e4921dc107caf533140112245e7a231d0edc49861cd779760ad4804e7034952a5cc79422fa9d31c54e9a6141fb4995af7a6bfce7a39140f@bootnode:30303"
      - "--gcmode=archive"
      - "--syncmode=full"
      - "--networkid=14000"
    volumes:
      - "./data/val3:/datadir"
      - "./genesis/testnet.json:/datadir/testnet.json"
      - "./genesis/keystore:/datadir/keystore"
      - "./genesis/password.txt:/datadir/password.txt"
    restart: always
  validator_4:
    image: energy
    command:
      - "geth"
      - "--datadir=/datadir"
      - "--genesis=/datadir/testnet.json"
      - "--mine"
      - "--password=/datadir/password.txt"
      - "--allow-insecure-unlock"
      - "--unlock=0x49c0f7c8c11a4c80dc6449efe1010bb166818da8"
      - "--miner.etherbase=0x49c0f7c8c11a4c80dc6449efe1010bb166818da8"
      - "--bootnodes=enode://5c8e90050fabb7e14e4921dc107caf533140112245e7a231d0edc49861cd779760ad4804e7034952a5cc79422fa9d31c54e9a6141fb4995af7a6bfce7a39140f@bootnode:30303"
      - "--gcmode=archive"
      - "--syncmode=full"
      - "--networkid=14000"
    volumes:
      - "./data/val4:/datadir"
      - "./genesis/testnet.json:/datadir/testnet.json"
      - "./genesis/keystore:/datadir/keystore"
      - "./genesis/password.txt:/datadir/password.txt"
    restart: always
  validator_5:
    image: energy
    command:
      - "geth"
      - "--datadir=/datadir"
      - "--genesis=/datadir/testnet.json"
      - "--mine"
      - "--password=/datadir/password.txt"
      - "--allow-insecure-unlock"
      - "--unlock=0x8e1ea6eaa09c3b40f4a51fcd056a031870a0549a"
      - "--miner.etherbase=0x8e1ea6eaa09c3b40f4a51fcd056a031870a0549a"
      - "--bootnodes=enode://5c8e90050fabb7e14e4921dc107caf533140112245e7a231d0edc49861cd779760ad4804e7034952a5cc79422fa9d31c54e9a6141fb4995af7a6bfce7a39140f@bootnode:30303"
      - "--gcmode=archive"
      - "--syncmode=full"
      - "--networkid=14000"
    volumes:
      - "./data/val5:/datadir"
      - "./genesis/testnet.json:/datadir/testnet.json"
      - "./genesis/keystore:/datadir/keystore"
      - "./genesis/password.txt:/datadir/password.txt"
    restart: always
  staking-ui:
    image: staking-ui
    environment:
      REACT_APP_ENVIRONMENT: "env"
      CHAIN_ID: "14000"
      CHAIN_NAME: "BAS devnet"
      CHAIN_RPC: "http://rpc.721.red:8545/"
      EXPLORER_HOME_URL: "https://explorer.${DOMAIN_NAME}/"
      EXPLORER_TX_URL: "https://explorer.${DOMAIN_NAME}/tx/{tx}"
      EXPLORER_ADDRESS_URL: "https://explorer.${DOMAIN_NAME}/address/{address}"
      EXPLORER_BLOCK_URL: "https://explorer.${DOMAIN_NAME}/block/{block}"
    ports:
      - "3001:80"
    restart: always

  db:
    image: postgres:13.6
    restart: always
    environment:
      POSTGRES_PASSWORD: ''
      POSTGRES_USER: 'postgres'
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    volumes:
      - ./data/postgres-data:/var/lib/postgresql/data
    ports:
      - "7432:5432"

  blockscout:
    depends_on:
      - db
    image: blockscout/blockscout:${DOCKER_TAG:-latest}
    restart: always
    links:
      - db:database
    command: 'mix do ecto.create, ecto.migrate, phx.server'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    #env_file:
    #  -  ./envs/common-blockscout.env
    environment:
      ETHEREUM_JSONRPC_VARIANT: 'geth'
      BLOCK_TRANSFORMER: 'base'
      ETHEREUM_JSONRPC_HTTP_URL: http://host.docker.internal:8545/
      DATABASE_URL: postgresql://postgres:@host.docker.internal:7432/blockscout?ssl=false
      ECTO_USE_SSL: 1
    ports:
      - "4000:4000"

  # nginx:
  #   image: nginx
  #   volumes:
  #     - /root/.acme.sh/:/root/.acme.sh/
  #     - ./nginx.conf:/etc/nginx/conf.d/00-default.conf
  #   ports:
  #     - "443:443"
  #   restart: always

volumes:
  postgresql_data: { }